functional:
  - пользователь может играть с ботом, другом или случайным игроком
  - есть возможность выбора языка программирования и уровня сложности

non-functional:
  - сайт должен быть удобен на мобильных устройствах
  - сайт должен быть протестирован на совместимость с современными браузерами

implicit:
  - у пользователя должно быть понимание, что происходит в игре (интерфейс должен быть интуитивным)
  - сайт должен сохранять историю игр, чтобы пользователь мог пересматривать
